### ISSUE TITLE
Notification styles

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#10]
_- we have 4 different types of notification, need to prepare a helper for it._

**Tasks:**
* global notification
* notification with cancel function
* notification inside of the content
* global alert notification
* initial notification stack

**Comment by illjah42** [comment]
Initial notification stack added in v1.1.1.
Usage:
```html
<system-notify-container ...other-props :notify="{title: 'Initial', message: 'message'}"></system-notify-container>
<!-- or -->
<system-notify-container ...other-props :notify="[{title: 'First', message: 'message'}, {title: 'Second', message: 'message'}]"></system-notify-container>
```
container will be rendered with notify inside
