### ISSUE TITLE
Feature request - Translatable fields

### ISSUE THREAD

**Issue by YannikFirre** [awes-io/awes-io#109]
Hello,

Do you plan to implement translatable fields with a package such as spatie/laravel-translatable ? 

Thanks 

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by yevhenlisovenko** [comment]
Hi @InfinityWebMe,
thanks for the question.
We will take this issue in the planning of the next sprint.
Best,
Yevhen
