### ISSUE TITLE
Problem with pkgkit

### ISSUE THREAD

**Issue by georgikolev7** [awes-io/awes-io#118]
After following the steps for installing the demo, is not loading correctly.
While checking the code, I saw what is causing this.

I'm attaching screenshot for more info, see the links.

![515151](https://user-images.githubusercontent.com/3003037/62271063-f0f06c80-b437-11e9-876b-7db80ecc583a.png)

**Comment by yevhenlisovenko** [comment]
Hey @suncho26 ,
you have to add a `PKGKIT_CDN_KEY` to your `.env` file.

There is a screenshot where you can find the key:
http://awescode.com/screenshots/Screenshot_01_08_19__10_01_22F2D40A.png

Please create a project on Package Kit to get the key.
If you didn't create a project, please follow the link: https://www.pkgkit.com/awes-io/create

Then please clear your cache: 
`php artisan cache:clear`

Best,
Yevhen

**Comment by georgikolev7** [comment]
Hey @yevhenlisovenko,

I add the `PKGKIT_CDN_KEY` to my `.env` file before my post here, but without effect.

Now everything is working correctly.
