### ISSUE TITLE
Stylus pack 4

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#12]
- [x] styles for the empty table (should be based on standard css elements);
- [x] bugs: http://awescode.com/screenshots/Screenshot_21_03_19__13_02_2243B4D0.png http://awescode.com/screenshots/Screenshot_21_03_19__13_02_2243B4D0.png
- [x] change pre loader image in multiselect from default
- [x] bottom in modal window should be bigger
- [x] `tb` toggle button in mobile version we have to see with another icon
- [x] `tb` remove word break in table
- [x] color in wave effect for light buttons need to change to grey
- [x] margin-right for icon in indigo-layout (./components/head/external-link.blade.php)

**Comment by AlexFN** [comment]
Done!
