### ISSUE TITLE
sidebar / navigator frame

### ISSUE THREAD

**Issue by anditsung** [awes-io/awes-io#132]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

after installing awes.io using the installer and create a new project
publish the awes/auth
php artisan vendor:publish --provider="AwesIO\Auth\AuthServiceProvider" --tag="views"
php artisan vendor:publish --provider="AwesIO\Auth\AuthServiceProvider" --tag="config"
php artisan vendor:publish --provider="AwesIO\Auth\AuthServiceProvider" --tag="migrations"

and 

i follow the guide here [https://www.awes.io/documentation/guide](url)

![Screen Shot 2019-08-15 at 10 50 38](https://user-images.githubusercontent.com/1090413/63071751-afd57d80-bf4a-11e9-934d-c4c869a369ef.png)

1. it seems that i dont have sidebar / navigator frame how to add it?
2. when making section, do we have to create the migration manualy?

need alot information regarding this platform

**Comment by begimov** [comment]
Hello, anditsung.
Thanks for your interest in the Awes.io platform.

Answering your questions:
1. Yes, you have to add sidebar, please follow instructions on https://github.com/awes-io/navigator, we'll also add it to awes.io platform and guides soon.
2. Yes, our package, which generates new sections doesn't generate any migrations, that said thanks for a great idea, we'll add this ability to a new version of Generator package.

I hope this helps, feel free to ask any questions. Thanks and have a nice day!

**Comment by anditsung** [comment]
the guide there is a bit different on awes demo

on the demo adding config/navigation.php
will automatically add to index.blade without passing it to view
```
<?php

return [
    'navs' => [
        'userNavigation' => [
            [
                'name' => 'Settings',
                'link' => '/settings',
            ],
            [
                'name' => 'Logout',
                'link' => '/logout',
                'class' => 'is-expand',
            ],
        ],
        'sidebar' => [
            [
                'name' => 'Dashboard',
                'link' => '/dashboard',
                'icon' => 'speed'
            ],
            [
                'name' => 'Leads',
                'link' => '/leads',
                'icon' => 'report'
            ],
            [
                'name' => 'Analytics',
                'link' => '/analytics',
                'icon' => 'report'
            ],
            [
                'name' => 'Settings',
                'link' => '/settings',
                'icon' => 'settings'
            ],
        ]
    ]
];
```

when i add this file to new project it will not showing the sidebar
and the account menu missing the setting and logout

![Screen Shot 2019-08-16 at 12 09 00](https://user-images.githubusercontent.com/1090413/63144791-bf25fb00-c01e-11e9-90d6-aaeea6607d58.png)

**Comment by begimov** [comment]
Thanks for your feedback, we'll be fixing these problems asap. Here are related issues, to track progress on #133, #134.

**Comment by begimov** [comment]
On navigation: after creating config/navigation.php file, please build and pass navigation in AppServiceProvider's boot method:

```php
View::composer('indigo-layout::main', function ($view) {
      $navs = \Navigator::buildMenu(config('navigation.navs'));
      $view->with('sidebar', $navs->children());
});
```
