### ISSUE TITLE
The data was not found.

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#16]
## Expected Behavior
In chart's components If the `datasets.data` is empty, should be shown empty slot.

## Current Behavior
Now we have an empty chart.

## Possible Solution
To add validation rules to `content-wrapper`

## Steps to Reproduce (for bugs)
1. open any chart and put inside empty `datasets.data` array

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by illjah42** [comment]
Now it's possible to customize emptiness validation function through `check-empty` prop of `<content-wrapper>`
Docs: https://git.awescode.com/awes-io/base-js/blob/dev/docs/content-wrapper.md
