### ISSUE TITLE
Static storage for virtual tour

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#20]
## Expected Behavior
The Vue.js part should save a cookie with a standard name `virtual-tour`.
Inside of the cookie should be JSON with a list of different virtual tours and end dates.
As well this cookie should be saved for all website.

- [x] cookie name `virtual-tour`
- [x] inside a JSON
- [x] end date inside of JSON
- [x] valid for all pages on the website

## Current Behavior
Different cookie name for different virtual tours.

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by illjah42** [comment]
What is changed:

- `name` prop is required now
- new `expires` prop to retry the tour after some *days*
- `AWES_CONFIG.virtualTour.cookieDomain` must be set to handle wildcard domains, like `.website.com`
