### ISSUE TITLE
A new position for modal windows

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#23]
## Expected Behavior
Control the position of the modal window.

* [ +] position: right (thin, normal, thick - width)
* [+ ] possibility to load a content inside of modal by Ajax
* [ ] ~~outside click (configuration), default like now~~

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)|https://github.com/awes-io/issues]

**Comment by yevhenlisovenko** [comment]
➤ Илья Китаев commented:

component: modal-window v1.1.0
styles: indigo-layout v1.9.2

**Comment by begimov** [comment]
As far as I understood these features has not been implemented yet in this task:

- possibility to load a content inside of modal by Ajax
-  outside click (configuration), default like now

or maybe info on their usage just absent from documentation?

**Comment by yevhenlisovenko** [comment]
➤ Ilya Kitayev commented:

v1.1.1
  * docs fullfilled with AJAX-modal example
  * globally configured‌bg-click-close prop added
