### ISSUE TITLE
Improvements for system-notify

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#24]
## Expected Behavior
- [x] Add additional options to the blade component.
- [x] manage buttons
- [x] possibility to add a custom HTML
- [x] add a small doc

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by begimov** [comment]
flex-grow: 1; */ remove & npm run build

**Comment by begimov** [comment]
https://git.awescode.com/awes-io/system-notify/merge_requests/11
