### ISSUE TITLE
Packaginator

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#25]
## Expected Behavior
Create a system for auto-creating sections in the project.

- [x] create a section
- [x] create a blade section

## Possible Solution
Should be an artisan commands to build everything.

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by begimov** [comment]
https://git.awescode.com/awes-io/generator
