### ISSUE TITLE
composer install Fail

### ISSUE THREAD

**Issue by dev3k** [awes-io/awes-io#256]
i wanted to try awes-io but `composer install` throwing below error , any idea why its happening ?

`  
[Composer\Downloader\TransportException]                                                                                             
  The "https://repo.pkgkit.com/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed                                                    
  Failed to enable crypto                                                                                                              
  failed to open stream: operation failed    
`

 i create pkgkit.com project and got my API-TOKEN and inserted into composer.json

OS: macOS Mojave
Composer version: 1.10.7
PHP version: 7.2.19

**Comment by yevhenlisovenko** [comment]
Hey @dev3k ,
now fixed! 
Best,
Yevhen
