### ISSUE TITLE
[table-builder] Sort by column value

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#30]
## Expected Behavior
If the column is possible to sort we show 2 arrows.
If the column already sorted:  http://awescode.com/screenshots/Screenshot_30_04_19__08_24_227821B7.png

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by illjah42** [comment]
logic: table-builder v1.2.0
styles: indigo-layout v1.9.1
