### ISSUE TITLE
Date-picker

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#31]
## Expected Behavior
Format:
`begin=2019-01-24&end=2019-01-26`

- [x] new element in form builder
- [x] ducumentation

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by illjah42** [comment]
component: form-builder v1.5.0
styles: indigo-layout v1.9.0

**Comment by yevhenlisovenko** [comment]
➤ Galymzhan Begimov commented:

If I use fb-date component like this:

```
<form-builder url="/api-url">
        <fb-date name="date" label="Pick a date"></fb-date>
</form-builder>
```

It’s all works fine, but if I use it like it’s explained in docs:

```
<form-builder url="/api-url">
        <fb-date label="Pick a date" min="2019-05-09" max="2019-06-20" value="2019-05-20"></fb-date>
</form-builder>
```

it fails with an error: TypeError: Cannot read property 'addEventListener' of null.

Looks like 'name' field is required, but not used in examples, maybe docs need an update.

**Comment by begimov** [comment]
Looks like preset value for date range dont work:

`<fb-date-range min="2019-05-09" max="2019-06-20" value-start="2019-05-15" value-end="2019-06-06"></fb-date-range>`

Above limits the possible range to select, but doesn't set start and end date on date pickers, and this one too:

```<fb-date-range name="date" value-start="2019-05-15" value-end="2019-05-26"></fb-date-range>```

**Comment by begimov** [comment]
After testing further, noticed an interesting moment:

```<fb-date label="Pick a date" min="2019-05-09" max="2019-06-20"></fb-date>```
```<fb-date label="Pick a date" min="2019-05-09" max="2019-06-20" value="2019-05-10"></fb-date>```

The first one works and the second one doesn't. Hope this helps.

**Comment by begimov** [comment]
```<fb-date name="date" label="Pick a date" yearRange="1"></fb-date>```

'yearRange' prop doesn't seem to do anything. And 'dayOffset' too:

```<fb-date name="date" label="Pick a date" min="05-02-2019" dayOffset=1></fb-date>```

Looks like "yearRange" doesn't work, but "year-range" does, maybe docs need an update.

**Comment by yevhenlisovenko** [comment]
➤ Ilya Kitayev commented:

v1.5.2:
  * fix: <date-range/> properly sets inital values (value-start and value-end props)
  * fix: docs examples rewritten for <form-builder/> usage (with name prop)
