### ISSUE TITLE
[virtual tour] after finish the tour, wrong z-index

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#36]
## Current status
After end of virtual tour we have z-index issue
![Снимок экрана 2019-04-28 в 10 46 22](https://user-images.githubusercontent.com/11060056/57121857-cfbda880-6d82-11e9-96e3-beaa87adcf64.png)

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by illjah42** [comment]
Update virtual-tour to v1.1.4 and indigo-layout to v1.7.6

**Comment by yevhenlisovenko** [comment]
**testing:** if the element not exists, the tour should be on the center.
