### ISSUE TITLE
[fb-select] Issue with loading additional results

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#37]
## Expected Behavior
Loading additional results to select.

## Current Behavior
https://gyazo.com/234b9757f23d9311c5f302affc6a1506

## Possible solution
change the name from `select-option` to `url` (was updated from v1.4.0)

## Steps to Reproduce (for bugs)
In `form-builder` v1.4.2 the bug exists. In `v1.3.23` not exists.

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by begimov** [comment]
https://git.awescode.com/pkgkit/pkgkit_www/merge_requests/181
