### ISSUE TITLE
Last version of v-tooltip

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#38]
## Current Behavior
The last version of v-tooltip makes an issue in the interface.
http://awescode.com/screenshots/List_of_your_projects____Package_Kit_228943B0.png
http://awescode.com/screenshots/Screenshot_13_05_19__10_15_22895F27.png

## Possible Solution
Include libs inside of indigo-layout.

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by illjah42** [comment]
fixed v-tooltip version to 2.x.x
