### ISSUE TITLE
[Demo] Virtual tour - hidden

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#47]
## Expected Behavior
show on the demo page

## Current Behavior
the virtual is hidden

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by begimov** [comment]
https://git.awescode.com/awes-io/demo/merge_requests/22
