### ISSUE TITLE
Table builder modification

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#54]
## Expected Behavior
- [ ] word-break: break-word; for the table: http://awescode.com/screenshots/Screenshot_23_05_19__09_22_229681CB.png
- [ ] horizontal scrool
- [ ] inherit cell scouped slot to mobile

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by yevhenlisovenko** [comment]
➤ Илья Китаев commented:

table-builder v1.2.2

indigo-layout v1.9.3

**Comment by begimov** [comment]
As far as I understood this feature has not been implemented yet in this task:

- inherit cell scouped slot to mobile

or maybe info on it usage just absent from documentation?
