### ISSUE TITLE
Undefined for version of packages

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#70]
Based on the issue: https://github.com/awes-io/demo/issues/1

## Expected Behavior
Base-js doesn't return version if PHP function `exec` is not exists.

## Current Behavior
Now the function returns `undefined`, should be a version of packages.

## Testing
Please check on XAMPP before and after the fix.

## System GA
[![Analytics](https://ga-beacon.appspot.com/UA-134431636-1/awes-io/issues)](https://github.com/awes-io/issues)

**Comment by x3rud** [comment]
There is an ETA about this problem?

**Comment by yevhenlisovenko** [comment]
Hey @mribera-erre2web,
we want to get the ticket for the next sprint. 
It means in max. 2 weeks it will be ready to use.

At the meantime, you can use the system inside of our Docker or in the system enabled `exec` function.
Best,
Yevhen

**Comment by yevhenlisovenko** [comment]
➤ Galymzhan Begimov commented:

https://git.awescode.com/awes-io/base-js/merge_requests/49 ( https://git.awescode.com/awes-io/base-js/merge_requests/49 )
