### ISSUE TITLE
SSL Network Error

### ISSUE THREAD

**Issue by yevhenlisovenko** [awes-io/awes-io#81]
When the user tries to install a new application thought installer, got the error: http://awescode.com/screenshots/Screenshot_27_06_19__18_46_22C52A80.png

**Comment by joelhmetz** [comment]
https://github.com/yabacon/paystack-php/wiki/cURL-error-60:-SSL-certificate-problem:-unable-to-get-local-issuer-certificate-(see-http:--curl.haxx.se-libcurl-c-libcurl-errors.html)
